
(function(){
'use strict';
var KEY='juslumeAccountingV3';
var db;
try{db=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}
if(!db)db={funds:[],invoices:[],bills:[],journals:[],periods:[],taxSales:[],taxPurchases:[],wht:[],banks:[],audit:[]};
['funds','invoices','bills','journals','periods','taxSales','taxPurchases','wht','banks','audit'].forEach(function(k){if(!Array.isArray(db[k]))db[k]=[]});
function save(){localStorage.setItem(KEY,JSON.stringify(db));window.__JUSLUME_V3_DB__=db;if(window.JuslumeCloud&&typeof window.JuslumeCloud.queuePush==='function')window.JuslumeCloud.queuePush(db)}
function id(p){return p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,7)}
function n(v){return Number(v||0)}
function money(v){return '฿'+n(v).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})}
function e(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function day(){return new Date().toISOString().slice(0,10)}
function td(d){return d?d.split('-').reverse().join('/'):'—'}
function actor(){return (window.office&&office.ownerEmail)||'ผู้ใช้ระบบ'}
function log(a,t,i,d){db.audit.unshift({at:new Date().toISOString(),actor:actor(),action:a,type:t,id:i||'',detail:d||''});save()}
function cases(){return (window.appData&&appData.cases||[]).map(function(x){return {id:x.id,label:[x.black,x.red,x.plaintiff].filter(Boolean).join(' • ')}})}
function caseLabel(i){var x=cases().find(function(c){return c.id===i});return x?x.label:'ไม่ผูกคดี'}
function caseOpts(){return '<option value="">ไม่ผูกคดี</option>'+cases().map(function(c){return '<option value="'+e(c.id)+'">'+e(c.label)+'</option>'}).join('')}
function closed(d){return db.periods.find(function(p){return p.status==='closed'&&d>=p.from&&d<=p.to})}
function openDate(d){var p=closed(d);if(p){alert('งวดบัญชี '+p.label+' ปิดแล้ว');return false}return true}
function no(prefix,arr){var y=new Date().getFullYear()+543;var c=arr.filter(function(x){return String(x.no||'').indexOf(prefix+'-'+y+'-')===0}).length+1;return prefix+'-'+y+'-'+String(c).padStart(6,'0')}
function jv(date,memo,source,lines){
 if(!openDate(date))return;
 var dr=lines.reduce(function(s,x){return s+n(x.debit)},0),cr=lines.reduce(function(s,x){return s+n(x.credit)},0);
 if(Math.abs(dr-cr)>.01){alert('เดบิตและเครดิตไม่เท่ากัน');return}
 var x={id:id('jv'),no:no('JV',db.journals),date:date,memo:memo,source:source,status:'posted',lines:lines};db.journals.unshift(x);log('POST','journal',x.id,memo);save();return x;
}
var coa={'1010':'เงินสด','1020':'เงินฝากธนาคาร','1030':'ลูกหนี้การค้า','1040':'ภาษีถูกหัก ณ ที่จ่าย','1050':'ภาษีซื้อ','2010':'เจ้าหนี้การค้า','2020':'เงินทดรองคดี','2030':'เงินของลูกความ','2040':'ภาษีขาย','2050':'ภาษีหัก ณ ที่จ่ายค้างจ่าย','4010':'รายได้ค่าทนายความ','4020':'รายได้ค่าปรึกษา','4030':'รายได้อื่น','5010':'ค่าใช้จ่ายคดี'};
function host(){var h=document.getElementById('v3Host');if(!h){h=document.createElement('section');h.id='v3Host';h.className='page hidden';document.querySelector('main').appendChild(h)}return h}
function top(a,b,c){return '<div class="topbar"><div><h1>'+a+'</h1><div class="sub">'+b+'</div></div><div class="top-actions">'+(c||'')+'</div></div>'}
function show(name){
 document.querySelectorAll('.page').forEach(function(x){x.classList.add('hidden')});host().classList.remove('hidden');
 document.querySelectorAll('aside nav button').forEach(function(x){x.classList.remove('active')});var b=document.querySelector('[data-v3="'+name+'"]');if(b)b.classList.add('active');
 ({funds:renderFunds,ar:renderAR,ap:renderAP,journal:renderJournal,trial:renderTrial,tax:renderTax,periods:renderPeriods,audit:renderAudit,banks:renderBanks,reports:renderReports}[name]||renderFunds)();window.scrollTo(0,0)
}
window.showAccountingV3=show;window.__JUSLUME_V3_DB__=db;window.getJuslumeV3State=function(){return db};
function style(){
 var s=document.createElement('style');s.textContent='.v3g{margin:13px 12px 5px;font-size:11px;opacity:.55}.v3stat{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.v3stat .card strong{display:block;font-size:20px;margin-top:6px}.v3table{overflow:auto}.v3table table{min-width:760px}.pill{display:inline-block;padding:4px 8px;border-radius:99px;background:#f1e6e8;font-size:11px}.pill.ok{background:#e8f5ee;color:#176b4b}.pill.warn{background:#fff3cd}.v3form{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.v3wide{grid-column:1/-1}@media(max-width:800px){.v3stat,.v3form{grid-template-columns:1fr 1fr}}@media(max-width:560px){.v3stat,.v3form{grid-template-columns:1fr}}';
 document.head.appendChild(s)
}
function nav(){
 var x=document.querySelector('aside nav');if(!x)return;
 x.innerHTML='<button class="active" data-page="dashboard">ภาพรวม</button><div class="v3g">งานคดี</div><button data-page="cases">รายละเอียดคดี</button><button data-v3="funds">เงินในคดี</button><div class="v3g">การเงิน</div><button data-page="receipts">ใบรับเงิน</button><button data-page="payments">ใบจ่ายเงิน</button><button data-v3="ar">ลูกหนี้ / ใบแจ้งหนี้</button><button data-v3="ap">เจ้าหนี้ / ใบตั้งหนี้</button><button data-v3="banks">เงินสดและธนาคาร</button><div class="v3g">บัญชี</div><button data-page="accounting">บัญชีรับ - จ่าย</button><button data-v3="journal">สมุดรายวัน</button><button data-v3="trial">งบทดลอง</button><button data-v3="periods">ปิดงวดบัญชี</button><div class="v3g">ภาษี</div><button data-v3="tax">VAT / WHT / 50 ทวิ</button><div class="v3g">ควบคุม</div><button data-v3="reports">รายงานบริหาร</button><button data-v3="audit">Audit Log</button><button data-page="office">ตั้งค่าสำนักงาน</button>';
 document.querySelectorAll('[data-v3]').forEach(function(b){b.onclick=function(){show(this.dataset.v3)}})
}
function renderFunds(){
 var office=0,advance=0,client=0;db.funds.forEach(function(x){var z=(x.dir==='in'?1:-1)*n(x.amount);if(x.bucket==='office')office+=z;if(x.bucket==='advance')advance+=z;if(x.bucket==='client')client+=z});
 host().innerHTML=top('เงินในคดี','แยกรายได้สำนักงาน เงินทดรอง และเงินของลูกความ','<button class="btn primary" onclick="fundForm()">+ บันทึกรายการ</button>')+
 '<div class="v3stat"><div class="card"><small>รายได้สำนักงาน</small><strong>'+money(office)+'</strong></div><div class="card"><small>เงินทดรองคงเหลือ</small><strong>'+money(advance)+'</strong></div><div class="card"><small>เงินของลูกความ</small><strong>'+money(client)+'</strong></div></div>'+
 '<div class="card v3table"><table><thead><tr><th>วันที่</th><th>คดี</th><th>ประเภท</th><th>รายการ</th><th>รับ</th><th>จ่าย</th><th>สถานะต้นทุน</th></tr></thead><tbody>'+(db.funds.length?db.funds.map(function(x){var t=x.bucket==='office'?'รายได้สำนักงาน':x.bucket==='advance'?'เงินทดรอง':'เงินของลูกความ';return '<tr><td>'+td(x.date)+'</td><td>'+e(caseLabel(x.caseId))+'</td><td>'+t+'</td><td>'+e(x.memo)+'</td><td>'+(x.dir==='in'?money(x.amount):'—')+'</td><td>'+(x.dir==='out'?money(x.amount):'—')+'</td><td>'+e(x.costStatus||'—')+'</td></tr>'}).join(''):'<tr><td colspan="7">ยังไม่มีข้อมูล</td></tr>')+'</tbody></table></div>'
}
window.fundForm=function(){
 host().innerHTML=top('บันทึกเงินในคดี','เงินทดรองและเงินของลูกความจะไม่ถูกนับเป็นรายได้สำนักงาน','<button class="btn" onclick="showAccountingV3(\'funds\')">← กลับ</button>')+
 '<div class="card"><div class="v3form"><label>วันที่<input id="fDate" type="date" value="'+day()+'"></label><label>คดี<select id="fCase">'+caseOpts()+'</select></label><label>ประเภทเงิน<select id="fBucket"><option value="office">รายได้สำนักงาน</option><option value="advance">เงินทดรองคดี</option><option value="client">เงินของลูกความ/รับแทน</option></select></label><label>รับ/จ่าย<select id="fDir"><option value="in">รับเข้า</option><option value="out">จ่ายออก</option></select></label><label>จำนวนเงิน<input id="fAmount" type="number" step="0.01"></label><label>สถานะค่าใช้จ่าย<select id="fCost"><option>สำนักงานรับผิดชอบ</option><option>เรียกเก็บจากลูกความ</option><option>ลูกความทดรองไว้แล้ว</option><option>สำนักงานสำรองจ่าย รอเบิกคืน</option><option>ไม่เรียกเก็บ</option></select></label><label class="v3wide">รายละเอียด<input id="fMemo"></label></div><div style="margin-top:15px"><button class="btn primary" onclick="saveFund()">บันทึก</button></div></div>'
};
window.saveFund=function(){
 var d=document.getElementById('fDate').value;if(!openDate(d))return;var a=n(document.getElementById('fAmount').value);if(a<=0)return alert('กรุณาระบุจำนวนเงิน');
 var x={id:id('fund'),date:d,caseId:document.getElementById('fCase').value,bucket:document.getElementById('fBucket').value,dir:document.getElementById('fDir').value,amount:a,memo:document.getElementById('fMemo').value,costStatus:document.getElementById('fCost').value};db.funds.unshift(x);
 var acc=x.bucket==='office'?(x.dir==='in'?'4010':'5010'):(x.bucket==='advance'?'2020':'2030');var lines=x.dir==='in'?[{account:'1020',debit:a,credit:0},{account:acc,debit:0,credit:a}]:[{account:acc,debit:a,credit:0},{account:'1020',debit:0,credit:a}];
 jv(d,x.memo,'fund:'+x.id,lines);log('CREATE','case_fund',x.id,x.memo);save();show('funds')
};
function calcInv(x){var base=n(x.base),vat=x.vat?base*.07:0,wht=base*n(x.whtRate)/100;return {base:base,vat:vat,wht:wht,gross:base+vat,net:base+vat-wht}}
function renderAR(){
 var out=db.invoices.reduce(function(s,x){return s+Math.max(0,calcInv(x).net-n(x.paid))},0);
 host().innerHTML=top('ลูกหนี้ / ใบแจ้งหนี้','ตั้งหนี้ก่อนรับเงินและติดตามยอดค้างรับ','<button class="btn primary" onclick="invoiceForm()">+ ใบแจ้งหนี้</button>')+'<div class="v3stat"><div class="card"><small>ลูกหนี้คงเหลือ</small><strong>'+money(out)+'</strong></div></div><div class="card v3table"><table><thead><tr><th>เลขที่</th><th>วันที่</th><th>ลูกความ</th><th>คดี</th><th>ยอดสุทธิ</th><th>รับแล้ว</th><th>ค้างรับ</th><th></th></tr></thead><tbody>'+(db.invoices.length?db.invoices.map(function(x){var c=calcInv(x),bal=c.net-n(x.paid);return '<tr><td>'+e(x.no)+'</td><td>'+td(x.date)+'</td><td>'+e(x.client)+'</td><td>'+e(caseLabel(x.caseId))+'</td><td>'+money(c.net)+'</td><td>'+money(x.paid)+'</td><td>'+money(bal)+'</td><td><button class="iconBtn" onclick="receiveInvoice(\''+x.id+'\')">รับชำระ</button></td></tr>'}).join(''):'<tr><td colspan="8">ยังไม่มีใบแจ้งหนี้</td></tr>')+'</tbody></table></div>'
}
window.invoiceForm=function(){
 host().innerHTML=top('ออกใบแจ้งหนี้','ระบบสร้างเลขเอกสารและบันทึกลูกหนี้อัตโนมัติ','<button class="btn" onclick="showAccountingV3(\'ar\')">← กลับ</button>')+'<div class="card"><div class="v3form"><label>เลขที่<input id="iNo" value="'+no('INV',db.invoices)+'"></label><label>วันที่<input id="iDate" type="date" value="'+day()+'"></label><label>ครบกำหนด<input id="iDue" type="date"></label><label>ลูกความ/ผู้รับบริการ<input id="iClient"></label><label>เลขผู้เสียภาษี<input id="iTax" maxlength="13"></label><label>สำนักงานใหญ่/สาขา<input id="iBranch" placeholder="สำนักงานใหญ่"></label><label>คดี<select id="iCase">'+caseOpts()+'</select></label><label>ประเภทบริการ<select id="iType"><option value="4010">ค่าทนายความ</option><option value="4020">ค่าปรึกษากฎหมาย</option><option value="4030">บริการอื่น</option></select></label><label>มูลค่าก่อน VAT<input id="iBase" type="number"></label><label>VAT<select id="iVat"><option value="1">7%</option><option value="0">ไม่มี VAT</option></select></label><label>WHT<select id="iWht"><option value="3">3%</option><option value="0">0%</option><option value="1">1%</option><option value="5">5%</option></select></label><label class="v3wide">ที่อยู่<textarea id="iAddr"></textarea></label></div><div style="margin-top:15px"><button class="btn primary" onclick="saveInvoice()">บันทึกใบแจ้งหนี้</button></div></div>'
};
window.saveInvoice=function(){
 var d=document.getElementById('iDate').value;if(!openDate(d))return;var x={id:id('inv'),no:document.getElementById('iNo').value,date:d,due:document.getElementById('iDue').value,client:document.getElementById('iClient').value,taxId:document.getElementById('iTax').value,branch:document.getElementById('iBranch').value,address:document.getElementById('iAddr').value,caseId:document.getElementById('iCase').value,account:document.getElementById('iType').value,base:n(document.getElementById('iBase').value),vat:document.getElementById('iVat').value==='1',whtRate:n(document.getElementById('iWht').value),paid:0};
 if(!x.client||x.base<=0)return alert('กรุณากรอกลูกความและยอดเงิน');if(db.invoices.some(function(z){return z.no===x.no}))return alert('เลขเอกสารซ้ำ');
 var c=calcInv(x);db.invoices.unshift(x);var lines=[{account:'1030',debit:c.gross,credit:0},{account:x.account,debit:0,credit:c.base}];if(c.vat)lines.push({account:'2040',debit:0,credit:c.vat});jv(d,'ตั้งลูกหนี้ '+x.no,'invoice:'+x.id,lines);if(c.vat)db.taxSales.unshift({date:d,no:x.no,name:x.client,taxId:x.taxId,base:c.base,vat:c.vat});
 log('ISSUE','invoice',x.id,x.no);save();show('ar')
};
window.receiveInvoice=function(i){var x=db.invoices.find(function(z){return z.id===i});if(!x)return;var c=calcInv(x),bal=c.net-n(x.paid);if(bal<=.01)return alert('ชำระครบแล้ว');var r=prompt('จำนวนเงินที่รับสุทธิ',String(bal));if(r===null)return;var a=n(r);if(a<=0||a>bal+.01)return alert('จำนวนไม่ถูกต้อง');x.paid=n(x.paid)+a;jv(day(),'รับชำระ '+x.no,'receipt:'+x.id,[{account:'1020',debit:a,credit:0},{account:'1030',debit:0,credit:a}]);log('RECEIVE','invoice',x.id,String(a));save();renderAR()};
function renderAP(){
 var out=db.bills.reduce(function(s,x){return s+Math.max(0,n(x.total)-n(x.paid))},0);
 host().innerHTML=top('เจ้าหนี้ / ใบตั้งหนี้','บันทึกค่าใช้จ่ายก่อนจ่ายและสร้าง 50 ทวิเมื่อมี WHT','<button class="btn primary" onclick="billForm()">+ ใบตั้งหนี้</button>')+'<div class="v3stat"><div class="card"><small>เจ้าหนี้คงเหลือ</small><strong>'+money(out)+'</strong></div></div><div class="card v3table"><table><thead><tr><th>เลขที่</th><th>วันที่</th><th>เจ้าหนี้</th><th>รายการ</th><th>ยอด</th><th>WHT</th><th>ค้างจ่าย</th><th></th></tr></thead><tbody>'+(db.bills.length?db.bills.map(function(x){return '<tr><td>'+e(x.no)+'</td><td>'+td(x.date)+'</td><td>'+e(x.vendor)+'</td><td>'+e(x.memo)+'</td><td>'+money(x.total)+'</td><td>'+x.whtRate+'%</td><td>'+money(n(x.total)-n(x.paid))+'</td><td><button class="iconBtn" onclick="payBill(\''+x.id+'\')">ชำระ</button></td></tr>'}).join(''):'<tr><td colspan="8">ยังไม่มีข้อมูล</td></tr>')+'</tbody></table></div>'
}
window.billForm=function(){host().innerHTML=top('ใบตั้งหนี้','เจ้าหนี้และค่าใช้จ่ายสำนักงาน','<button class="btn" onclick="showAccountingV3(\'ap\')">← กลับ</button>')+'<div class="card"><div class="v3form"><label>เลขที่<input id="bNo" value="'+no('BILL',db.bills)+'"></label><label>วันที่<input id="bDate" type="date" value="'+day()+'"></label><label>เจ้าหนี้<input id="bVendor"></label><label>เลขผู้เสียภาษี<input id="bTax"></label><label>ประเภทผู้รับ<select id="bType"><option value="person">บุคคลธรรมดา</option><option value="company">นิติบุคคล</option></select></label><label>คดี<select id="bCase">'+caseOpts()+'</select></label><label>มูลค่าก่อน VAT<input id="bBase" type="number"></label><label>VAT ซื้อ<select id="bVat"><option value="0">ไม่มี</option><option value="1">7%</option></select></label><label>WHT<select id="bWht"><option value="0">0%</option><option value="1">1%</option><option value="3">3%</option><option value="5">5%</option></select></label><label class="v3wide">รายละเอียด<input id="bMemo"></label></div><div style="margin-top:15px"><button class="btn primary" onclick="saveBill()">บันทึก</button></div></div>'};
window.saveBill=function(){var d=document.getElementById('bDate').value;if(!openDate(d))return;var base=n(document.getElementById('bBase').value),vat=document.getElementById('bVat').value==='1'?base*.07:0;if(base<=0)return alert('กรุณาระบุยอด');var x={id:id('bill'),no:document.getElementById('bNo').value,date:d,vendor:document.getElementById('bVendor').value,taxId:document.getElementById('bTax').value,vendorType:document.getElementById('bType').value,caseId:document.getElementById('bCase').value,base:base,vat:vat,total:base+vat,whtRate:n(document.getElementById('bWht').value),memo:document.getElementById('bMemo').value,paid:0};db.bills.unshift(x);var lines=[{account:'5010',debit:base,credit:0},{account:'2010',debit:0,credit:x.total}];if(vat)lines.push({account:'1050',debit:vat,credit:0});jv(d,'ตั้งเจ้าหนี้ '+x.no,'bill:'+x.id,lines);if(vat)db.taxPurchases.unshift({date:d,no:x.no,name:x.vendor,taxId:x.taxId,base:base,vat:vat});log('CREATE','bill',x.id,x.no);save();show('ap')};
window.payBill=function(i){var x=db.bills.find(function(z){return z.id===i});if(!x)return;if(n(x.paid)>=n(x.total)-.01)return alert('ชำระครบแล้ว');var w=x.base*x.whtRate/100,net=x.total-w;x.paid=x.total;jv(day(),'ชำระ '+x.no,'payment:'+x.id,[{account:'2010',debit:x.total,credit:0},{account:'1020',debit:0,credit:net},{account:'2050',debit:0,credit:w}]);if(x.whtRate>0)db.wht.unshift({no:no('WHT',db.wht),date:day(),payee:x.vendor,taxId:x.taxId,form:x.vendorType==='company'?'ภ.ง.ด.53':'ภ.ง.ด.3',base:x.base,rate:x.whtRate,tax:w});log('PAY','bill',x.id,String(net));save();renderAP()};
function renderJournal(){host().innerHTML=top('สมุดรายวัน','บัญชีคู่ — รายการ Post แล้วไม่ลบ ให้กลับรายการแทน')+'<div class="card v3table"><table><thead><tr><th>เลขที่</th><th>วันที่</th><th>รายการ</th><th>เดบิต</th><th>เครดิต</th><th></th></tr></thead><tbody>'+(db.journals.length?db.journals.map(function(x){var d=x.lines.reduce(function(s,z){return s+n(z.debit)},0),c=x.lines.reduce(function(s,z){return s+n(z.credit)},0);return '<tr><td>'+x.no+'</td><td>'+td(x.date)+'</td><td>'+e(x.memo)+'</td><td>'+money(d)+'</td><td>'+money(c)+'</td><td><button class="iconBtn" onclick="reverseJV(\''+x.id+'\')">กลับรายการ</button></td></tr>'}).join(''):'<tr><td colspan="6">ยังไม่มีรายการ</td></tr>')+'</tbody></table></div>'}
window.reverseJV=function(i){var x=db.journals.find(function(z){return z.id===i});if(!x)return;var r=prompt('เหตุผลการกลับรายการ');if(!r)return;jv(day(),'กลับรายการ '+x.no+' — '+r,'reverse:'+x.id,x.lines.map(function(z){return {account:z.account,debit:n(z.credit),credit:n(z.debit)}}));log('REVERSE','journal',x.id,r);renderJournal()};
function trial(){var m={};Object.keys(coa).forEach(function(k){m[k]={code:k,name:coa[k],dr:0,cr:0}});db.journals.forEach(function(j){j.lines.forEach(function(x){if(!m[x.account])m[x.account]={code:x.account,name:x.account,dr:0,cr:0};m[x.account].dr+=n(x.debit);m[x.account].cr+=n(x.credit)})});return Object.values(m)}
function renderTrial(){var a=trial(),dr=a.reduce(function(s,x){return s+x.dr},0),cr=a.reduce(function(s,x){return s+x.cr},0);host().innerHTML=top('งบทดลอง','ตรวจสอบยอดเดบิตและเครดิต')+'<div class="card v3table"><table><thead><tr><th>รหัส</th><th>บัญชี</th><th>เดบิต</th><th>เครดิต</th><th>คงเหลือ</th></tr></thead><tbody>'+a.map(function(x){return '<tr><td>'+x.code+'</td><td>'+e(x.name)+'</td><td>'+money(x.dr)+'</td><td>'+money(x.cr)+'</td><td>'+money(Math.abs(x.dr-x.cr))+' '+(x.dr>=x.cr?'Dr':'Cr')+'</td></tr>'}).join('')+'<tr><th colspan="2">รวม</th><th>'+money(dr)+'</th><th>'+money(cr)+'</th><th>'+(Math.abs(dr-cr)<.01?'สมดุล':'ไม่สมดุล')+'</th></tr></tbody></table></div>'}
function renderTax(){var sv=db.taxSales.reduce(function(s,x){return s+n(x.vat)},0),pv=db.taxPurchases.reduce(function(s,x){return s+n(x.vat)},0);host().innerHTML=top('ศูนย์ภาษี','ภาษีขาย ภาษีซื้อ ภ.พ.30 และทะเบียน 50 ทวิ / ภ.ง.ด.3 / ภ.ง.ด.53')+'<div class="v3stat"><div class="card"><small>ภาษีขาย</small><strong>'+money(sv)+'</strong></div><div class="card"><small>ภาษีซื้อ</small><strong>'+money(pv)+'</strong></div><div class="card"><small>VAT สุทธิ</small><strong>'+money(sv-pv)+'</strong></div><div class="card"><small>50 ทวิ</small><strong>'+db.wht.length+'</strong></div></div><div class="card v3table"><h3>ทะเบียนหัก ณ ที่จ่าย</h3><table><thead><tr><th>50 ทวิ</th><th>วันที่</th><th>ผู้รับ</th><th>แบบ</th><th>ฐาน</th><th>อัตรา</th><th>ภาษี</th></tr></thead><tbody>'+(db.wht.length?db.wht.map(function(x){return '<tr><td>'+x.no+'</td><td>'+td(x.date)+'</td><td>'+e(x.payee)+'</td><td>'+x.form+'</td><td>'+money(x.base)+'</td><td>'+x.rate+'%</td><td>'+money(x.tax)+'</td></tr>'}).join(''):'<tr><td colspan="7">ยังไม่มีข้อมูล</td></tr>')+'</tbody></table></div>'}
function renderPeriods(){host().innerHTML=top('ปิดงวดบัญชี','งวดปิดแล้วห้ามแก้รายการตรง ๆ','<button class="btn primary" onclick="closePeriod()">+ ปิดงวด</button>')+'<div class="card v3table"><table><thead><tr><th>งวด</th><th>เริ่ม</th><th>สิ้นสุด</th><th>สถานะ</th><th></th></tr></thead><tbody>'+(db.periods.length?db.periods.map(function(x){return '<tr><td>'+e(x.label)+'</td><td>'+td(x.from)+'</td><td>'+td(x.to)+'</td><td><span class="pill '+(x.status==='closed'?'warn':'ok')+'">'+(x.status==='closed'?'ปิด':'เปิด')+'</span></td><td>'+(x.status==='closed'?'<button class="iconBtn" onclick="openPeriod(\''+x.id+'\')">ขอเปิดงวด</button>':'')+'</td></tr>'}).join(''):'<tr><td colspan="5">ยังไม่มีข้อมูล</td></tr>')+'</tbody></table></div>'}
window.closePeriod=function(){var label=prompt('ชื่องวด เช่น กันยายน 2569');if(!label)return;var from=prompt('วันที่เริ่ม YYYY-MM-DD');if(!from)return;var to=prompt('วันที่สิ้นสุด YYYY-MM-DD');if(!to)return;var x={id:id('period'),label:label,from:from,to:to,status:'closed'};db.periods.unshift(x);log('CLOSE_PERIOD','period',x.id,label);save();renderPeriods()};
window.openPeriod=function(i){var x=db.periods.find(function(z){return z.id===i});if(!x)return;var r=prompt('เหตุผลการเปิดงวด');if(!r)return;var fn=function(){x.status='open';x.reason=r;log('OPEN_PERIOD','period',x.id,r);save();renderPeriods()};if(typeof requestSecureAction==='function')requestSecureAction('เปิดงวดบัญชี '+x.label,fn);else fn()};
function renderBanks(){host().innerHTML=top('เงินสดและธนาคาร','ทะเบียนบัญชีและกระทบยอดกับ Statement','<button class="btn primary" onclick="addBank()">+ เพิ่มบัญชี</button>')+'<div class="card v3table"><table><thead><tr><th>ธนาคาร</th><th>ชื่อบัญชี</th><th>เลขบัญชี</th><th>ยอดตามระบบ</th><th>ยอด Statement</th><th>ผลต่าง</th></tr></thead><tbody>'+(db.banks.length?db.banks.map(function(x){return '<tr><td>'+e(x.bank)+'</td><td>'+e(x.name)+'</td><td>'+e(x.no)+'</td><td>'+money(x.system)+'</td><td>'+money(x.statement)+'</td><td>'+money(n(x.statement)-n(x.system))+'</td></tr>'}).join(''):'<tr><td colspan="6">ยังไม่มีบัญชีธนาคาร</td></tr>')+'</tbody></table></div>'}
window.addBank=function(){var bank=prompt('ธนาคาร');if(!bank)return;var x={id:id('bank'),bank:bank,name:prompt('ชื่อบัญชี')||'',no:prompt('เลขบัญชี')||'',system:n(prompt('ยอดตามระบบ','0')),statement:n(prompt('ยอดตาม Statement','0'))};db.banks.push(x);log('CREATE','bank',x.id,bank);save();renderBanks()};

function renderReports(){
 var income=0,advance=0,client=0;
 db.funds.forEach(function(x){var a=(x.dir==='in'?1:-1)*n(x.amount);if(x.bucket==='office')income+=a;if(x.bucket==='advance')advance+=a;if(x.bucket==='client')client+=a});
 var expense=db.bills.reduce(function(s,x){return s+n(x.base)},0);
 var ar=db.invoices.reduce(function(s,x){return s+Math.max(0,calcInv(x).net-n(x.paid))},0);
 var ap=db.bills.reduce(function(s,x){return s+Math.max(0,n(x.total)-n(x.paid))},0);
 var caseIds={};cases().forEach(function(x){caseIds[x.id]=true});db.funds.forEach(function(x){if(x.caseId)caseIds[x.caseId]=true});db.invoices.forEach(function(x){if(x.caseId)caseIds[x.caseId]=true});db.bills.forEach(function(x){if(x.caseId)caseIds[x.caseId]=true});
 var rows=Object.keys(caseIds).map(function(cid){
   var revenue=db.invoices.filter(function(x){return x.caseId===cid}).reduce(function(s,x){return s+calcInv(x).base},0);
   revenue+=db.funds.filter(function(x){return x.caseId===cid&&x.bucket==='office'}).reduce(function(s,x){return s+(x.dir==='in'?n(x.amount):-n(x.amount))},0);
   var cost=db.bills.filter(function(x){return x.caseId===cid}).reduce(function(s,x){return s+n(x.base)},0);
   cost+=db.funds.filter(function(x){return x.caseId===cid&&x.bucket==='office'&&x.dir==='out'}).reduce(function(s,x){return s+n(x.amount)},0);
   var adv=db.funds.filter(function(x){return x.caseId===cid&&x.bucket==='advance'}).reduce(function(s,x){return s+(x.dir==='in'?n(x.amount):-n(x.amount))},0);
   var cli=db.funds.filter(function(x){return x.caseId===cid&&x.bucket==='client'}).reduce(function(s,x){return s+(x.dir==='in'?n(x.amount):-n(x.amount))},0);
   return '<tr><td>'+e(caseLabel(cid))+'</td><td>'+money(revenue)+'</td><td>'+money(cost)+'</td><td>'+money(revenue-cost)+'</td><td>'+money(adv)+'</td><td>'+money(cli)+'</td></tr>';
 }).join('');
 host().innerHTML=top('รายงานบริหาร','ภาพรวมสำนักงาน กำไร–ขาดทุน ลูกหนี้ เจ้าหนี้ และผลประกอบการรายคดี','<button class="btn" onclick="exportManagementCSV()">ส่งออก CSV</button>')+
 '<div class="v3stat"><div class="card"><small>รายได้สำนักงาน</small><strong>'+money(income)+'</strong></div><div class="card"><small>ค่าใช้จ่ายตั้งหนี้</small><strong>'+money(expense)+'</strong></div><div class="card"><small>กำไรโดยประมาณ</small><strong>'+money(income-expense)+'</strong></div><div class="card"><small>ลูกหนี้ / เจ้าหนี้</small><strong>'+money(ar)+' / '+money(ap)+'</strong></div></div>'+
 '<div class="card v3table"><h3>กำไรและเงินคงเหลือรายคดี</h3><table><thead><tr><th>คดี</th><th>รายได้</th><th>ต้นทุน</th><th>กำไร</th><th>เงินทดรองคงเหลือ</th><th>เงินลูกความคงเหลือ</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6">ยังไม่มีข้อมูล</td></tr>')+'</tbody></table></div>';
}
window.exportManagementCSV=function(){
 var rows=[['คดี','รายได้','ต้นทุน','กำไร','เงินทดรอง','เงินลูกความ']];
 var ids={};cases().forEach(function(x){ids[x.id]=1});db.funds.forEach(function(x){if(x.caseId)ids[x.caseId]=1});db.invoices.forEach(function(x){if(x.caseId)ids[x.caseId]=1});db.bills.forEach(function(x){if(x.caseId)ids[x.caseId]=1});
 Object.keys(ids).forEach(function(cid){
   var revenue=db.invoices.filter(function(x){return x.caseId===cid}).reduce(function(s,x){return s+calcInv(x).base},0);
   revenue+=db.funds.filter(function(x){return x.caseId===cid&&x.bucket==='office'}).reduce(function(s,x){return s+(x.dir==='in'?n(x.amount):-n(x.amount))},0);
   var cost=db.bills.filter(function(x){return x.caseId===cid}).reduce(function(s,x){return s+n(x.base)},0);
   var adv=db.funds.filter(function(x){return x.caseId===cid&&x.bucket==='advance'}).reduce(function(s,x){return s+(x.dir==='in'?n(x.amount):-n(x.amount))},0);
   var cli=db.funds.filter(function(x){return x.caseId===cid&&x.bucket==='client'}).reduce(function(s,x){return s+(x.dir==='in'?n(x.amount):-n(x.amount))},0);
   rows.push([caseLabel(cid),revenue,cost,revenue-cost,adv,cli]);
 });
 var csv='\ufeff'+rows.map(function(r){return r.map(function(v){return '"'+String(v==null?'':v).replace(/"/g,'""')+'"'}).join(',')}).join('\n');
 var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='JUSLUME-MANAGEMENT-'+day()+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)
}

function renderAudit(){host().innerHTML=top('Audit Log','ประวัติการสร้าง Post กลับรายการ ปิดงวด และเปิดงวด')+'<div class="card v3table"><table><thead><tr><th>วันเวลา</th><th>ผู้ใช้</th><th>เหตุการณ์</th><th>ประเภท</th><th>รายละเอียด</th></tr></thead><tbody>'+(db.audit.length?db.audit.map(function(x){return '<tr><td>'+new Date(x.at).toLocaleString('th-TH')+'</td><td>'+e(x.actor)+'</td><td>'+e(x.action)+'</td><td>'+e(x.type)+'</td><td>'+e(x.detail)+'</td></tr>'}).join(''):'<tr><td colspan="5">ยังไม่มีข้อมูล</td></tr>')+'</tbody></table></div>'}
function patchDelete(){window.requestDelete=function(group,i,label){if(group==='receipts'||group==='payments'){log('BLOCK_DELETE',group,i,label);return alert('เอกสารการเงินที่ยืนยันแล้วไม่อนุญาตให้ลบ ให้ยกเลิกหรือกลับรายการเพื่อคง Audit Trail')}var fn=function(){if(window.appData&&appData[group]){appData[group]=appData[group].filter(function(x){return x.id!==i});if(typeof saveAppData==='function')saveAppData();if(typeof renderData==='function')renderData();log('DELETE',group,i,label)}};if(typeof requestSecureAction==='function')requestSecureAction('ลบ '+label,fn);else fn()}}
function dashboard(){var sec=document.getElementById('v3dash');if(!sec){sec=document.createElement('div');sec.id='v3dash';sec.className='section';var d=document.getElementById('dashboard');var before=d&&d.querySelector('.section');if(d)d.insertBefore(sec,before)}if(!sec)return;var off=0,adv=0,cli=0;db.funds.forEach(function(x){var a=(x.dir==='in'?1:-1)*n(x.amount);if(x.bucket==='office')off+=a;if(x.bucket==='advance')adv+=a;if(x.bucket==='client')cli+=a});var ar=db.invoices.reduce(function(s,x){return s+Math.max(0,calcInv(x).net-n(x.paid))},0);sec.innerHTML='<div class="card"><div class="head"><h2>บัญชีสำนักงาน V3</h2></div><div class="v3stat"><div><small>รายได้สำนักงาน</small><strong>'+money(off)+'</strong></div><div><small>เงินทดรองคดี</small><strong>'+money(adv)+'</strong></div><div><small>เงินของลูกความ</small><strong>'+money(cli)+'</strong></div><div><small>ลูกหนี้คงเหลือ</small><strong>'+money(ar)+'</strong></div></div></div>'}
style();nav();host();patchDelete();dashboard();
var banner=document.getElementById('testModeBanner');if(banner)banner.textContent='JUSLUME ACCOUNTING V3 — เอกสารการเงินที่ยืนยันแล้วไม่ลบโดยตรง • โหมดทดลองยังเก็บข้อมูลในเบราว์เซอร์จนกว่าจะเชื่อม Supabase ตาม schema.sql';
log('BOOT','system','v3','Accounting V3 loaded');
var cloudScript=document.createElement('script');cloudScript.src='cloud.js';cloudScript.defer=true;document.body.appendChild(cloudScript);
})();